### ISSUE TITLE
Not working with Metro M0 Express

### ISSUE THREAD

**Issue by aedsinger** [adafruit/Adafruit_NeoPixel_ZeroDMA#6]
Running Adafruit_NeoPixel_ZeroDMA on an Adafruit Metro M0 causes the board to crash (main loop stops, USB goes away). 

Running versions:

v1.04 Adafruit DMA neopixel library
v1.1.6 Adafruit Neopixel library
v1.0.1 Adafruit Zero DMA library

The following causes the issue (using the on-board NeoPixel of the Metro M0 Express)

#include <Adafruit_NeoPixel_ZeroDMA.h>
Adafruit_NeoPixel_ZeroDMA strip(1, 40, NEO_GRB);

void setup() {
  strip.begin();
  strip.setBrightness(32);
  strip.show();
}

void loop()
{
      strip.setPixelColor(0,125,125,0);
      strip.show();
      delay(2000);
      strip.setPixelColor(0,125,0,125);
      strip.show();
      delay(2000);
}

**Comment by PaintYourDragon** [comment]
DMA NeoPixels are available only on certain pins. As shown in the example sketch, here's what works on the Metro M0 Express (pinout is functionally very similar to Arduino Zero):

`// On Feather M0, Arduino Zero, etc.: 5, 11, A5 and 23 (SPI MOSI).`

If unsure, you can check the return value of strip.begin(), it will return false if the pin is not DMA-capable. This is being ignored in the example code, which is why it crashes...the program is attempting to modify non-allocated buffers.
